config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#top', as: 'route'

  post 'likes/:post_id/create', to: 'likes#create', as: 'like'
  delete 'likes/:post_id/destroy', to: 'likes#destroy', as: 'unlike'

  get 'posts/index'
  get 'posts/new', to: 'posts#new'
  get 'posts/:id/edit', to: 'posts#edit', as: 'posts_edit'
  post 'posts/create', to: 'posts#create'
  post 'posts/:id/update', to: 'posts#update', as: 'posts_update'
  delete 'posts/:id/delete', to: 'posts#destroy', as: 'posts_delete'

  get 'users/index'
  get 'users/:id', to: 'users#show', as: 'users_show'
  get 'users/:id/likes', to: 'users#likes', as: 'users_likes'
  get 'users/:id/edit', to: 'users#edit', as: 'users_edit'
  get 'signup', to: 'users#signup'
  get 'login', to: 'users#login_form'
  get 'users/:id/following', to: 'users#following'
  get 'users/:id/followers', to: 'users#followers'
  post 'users/create', to: 'users#create'
  post 'users/:id/update', to: 'users#update'
  post 'login', to: 'users#login'
  post 'logout', to: 'users#logout'

  resources :users do
    resource :relationships, only: %i[create destroy]
    get :follow, on: :member
    get :followers, on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: { message: 'ユーザー名は必須項目です' }
  validates :email, presence: { message: 'メールアドレスは必須項目です' }
  validates :email, uniqueness: { message: 'このメールアドレスはすでに登録済みです' }
  validates :password, presence: { message: 'パスワードは必須項目です' }

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  def find_posts(page)
    posts.includes(:likes).order(created_at: :desc).page(page).per(10)
  end

  def find_liked_posts(page)
    liked_posts.includes(%i[user likes]).order('likes.created_at DESC').page(page).per(10)
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, { only: %i[show] }
  before_action :forbid_login_user, { only: %i[login login_form signup create] }
  before_action :ensure_current_user, { only: %i[edit update] }
  before_action :get_following_users_and_followers, { only: %i[show likes] }

  def index
    @users = User.all
  end

  def show
    @posts = @user.find_posts(params[:page])
    @posts_liked_by_current_user = @current_user.likes.pluck(:post_id)
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = '該当のユーザーが見つかりませんでした'
    redirect_to users_index_path
  rescue StandardError
    flash[:notice] = 'プロフィール画面の表示に失敗しました'
    redirect_to users_index_path
  end

  def likes
    @liked_posts = @user.find_liked_posts(params[:page])
    @posts_liked_by_current_user = @current_user.likes.pluck(:post_id)
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = '該当のユーザーが見つかりませんでした'
    redirect_to users_index_path
  rescue StandardError
    flash[:notice] = 'いいね一覧の表示に失敗しました'
    redirect_to users_index_path
  end

  def signup
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save!
    session[:user_id] = @user.id
    flash[:notice] = 'ユーザー登録が完了しました。'
    redirect_to("/users/#{@user.id}")
  rescue ActiveRecord::RecordInvalid
    render :signup, status: :unprocessable_entity
  rescue StandardError
    flash[:notice] = 'ユーザー登録に失敗しました'
    redirect_to users_index_path
  end

  def edit
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = '該当のユーザーが見つかりませんでした'
    redirect_to users_index_path
  rescue StandardError
    flash[:notice] = 'ユーザーの表示に失敗しました'
    redirect_to users_index_path
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    flash[:notice] = 'ユーザー情報を変更しました'
    redirect_to("/users/#{@user.id}")
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = '該当のユーザーが見つかりませんでした'
    redirect_to users_index_path
  rescue ActiveRecord::RecordInvalid
    render :edit, status: :unprocessable_entity
  rescue StandardError
    flash[:notice] = 'ユーザー情報の更新に失敗しました'
    redirect_to users_index_path
  end

  def login_form; end

  def login
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = 'ログインしました。'
      redirect_to('/posts/index')
    else
      @error_message = 'メールアドレスまたはパスワードが間違っています'
      @email = params[:email]
      @password = params[:password]
      render :login_form, status: :unprocessable_entity
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'ログアウトしました。'
    redirect_to('/login')
  end

  def follow
    user = User.find(params[:id])
    @users = user.followings
    @follows_count = @users.count
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = '該当のユーザーが見つかりませんでした'
    redirect_to users_index_path
  rescue StandardError
    flash[:notice] = 'フォロー一覧の表示に失敗しました'
    redirect_to users_index_path
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
    @followers_count = @users.count
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = '該当のユーザーが見つかりませんでした'
    redirect_to users_index_path
  rescue StandardError
    flash[:notice] = 'フォロワー一覧の表示に失敗しました'
    redirect_to users_indext_path
  end

  private

  def user_params
    params.permit(:username, :email, :password, :password_confirmation)
  end

  def find_following_users_and_followers
    @user = User.find(params[:id])
    @followings = @user.followings
    @followers = @user.followers
    @following_count = @followings.count
    @follower_count = @followers.count
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_tag(path) do %>
    <div class="formWrapper">
        <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |message| %>
                <div class="formError">
                <%= message %>
                </div>
            <% end %>
        <% end %>
        <p>ユーザー名</p>
        <input name="username" type="text" value="<%= @user.username %>">
        <p>メールアドレス</p>
        <input name="email" type="text" value="<%= @user.email %>">
        <p>パスワード</p>
        <input name="password" type="password">
        <p>確認用パスワード(パスワードを再度入力してください)</p>
        <input name="password_confirmation" type="password">
        <input type="submit" value="登録">
    </div>
<% end %>

app/views/users/_user_list.html.erb
<ul class="userList">
    <% @users.each do |user| %>
        <%= link_to users_show_path(user.id) do %>
            <li class="userItem">
                <p><%= user.username %></p>
            </li>
        <% end %>
    <% end %>
</ul>

app/views/users/edit.html.erb
<div class="editPage">
    <%= render partial: "form", locals: {path: "/users/#{params[:id]}/update"} %>
</div>

app/views/users/follow.html.erb
<div class="userListPage">
    <h2 class="userTtl">フォロー一覧</h2>
    <%= render partial: "user_list", collections: @users %>
</div>

app/views/users/followers.html.erb
<div class="userListPage">
    <h2 class="userTtl">フォロワー一覧</h2>
    <%= render partial: "user_list", collections: @users %>
</div>

app/views/users/index.html.erb
<div class="userListPage">
    <h2 class="userTtl">ユーザー一覧</h2>
    <%= render partial: "user_list", collections: @users %>
</div>

app/views/users/likes.html.erb
<div class="userWrapper">
    <h2 class="username">
        <%= @user.username %>
    </h2>
    <p class="userEdit">
        <% if @current_user.id == @user.id%>
            <%= link_to "ユーザー情報を編集", users_edit_path(@current_user.id) %>
        <% else %>
            <% if @user.followed_by?(@current_user) %>
                <%= link_to "フォロー済", user_relationships_path(@user.id), data: {turbo_method: :delete} %>
            <% else%>
                <%= link_to "フォローする", user_relationships_path(@user.id), data: {turbo_method: :post} %>
            <% end %>
        <% end %>
    </p>
    <div class="followWrapper">
        <div class="followWrapper">
            <%= link_to follow_user_path(@user.id) do %>
                <p>
                        フォロー <%= @following_count %>
                </p>
            <% end %>
            <%= link_to followers_user_path(@user.id) do %>
                <p>
                        フォロワー <%= @follower_count %>
                </p>
            <% end %>
        </div>
    </div>
</div>
<div class="postsContainer">
    <div class="tabMenu">
        <p><%= link_to "投稿", users_show_path(@user.id) %></p>
        <p class="active">いいね！</p>
    </div>
    <ul class="postList">
        <%= render partial: 'shared/posts_index', collection: @liked_posts, as: 'post' %>
    </ul>
    <%= paginate @liked_posts %>
</div>

app/views/users/login_form.html.erb
<div class="loginPage">
    <%= form_tag("/login") do %>
    <div class="loginForm">
        <% if @error_message %>
            <%= @error_message %>
        <% end %>
        <p>メールアドレス</p>
        <input name="email" type="text">
        <p>パスワード</p>
        <input name="password" type="password">
        <input type="submit" value="送信">
    </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="userWrapper">
    <h2 class="username">
        <%= @user.username %>
    </h2>
    <p class="userEdit">
        <% if @current_user.id == @user.id%>
            <%= link_to "ユーザー情報を編集", users_edit_path(@current_user.id) %>
        <% else%>
            <% if @user.followed_by?(@current_user) %>
                <%= link_to "フォロー済", user_relationships_path(@user.id), data: {turbo_method: :delete} %>
            <% else%>
                <%= link_to "フォローする", user_relationships_path(@user.id), data: {turbo_method: :post} %>
            <% end %>
        <% end %>
    </p>
    <div class="followWrapper">
        <%= link_to follow_user_path(@user.id) do %>
            <p>
                    フォロー <%= @following_count %>
            </p>
        <% end %>
        <%= link_to followers_user_path(@user.id) do %>
            <p>
                    フォロワー <%= @follower_count %>
            </p>
        <% end %>
    </div>
</div>
<div class="postsContainer">
    <div class="tabMenu">
        <p class="active">投稿</p>
        <p><%= link_to "いいね！", users_likes_path(@user.id) %></p>
    </div>
    <ul class="postList">
        <%= render partial: 'shared/posts_index', collection: @posts, as: 'post' %>
    </ul>
    <%= paginate @posts%>
</div>

app/views/users/signup.html.erb
<div class="loginPage">
    <%= render partial: "form", locals: {path: "/users/create"} %>
</div>