config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#top', as: 'route'

  post 'likes/:post_id/create', to: 'likes#create', as: 'like'
  delete 'likes/:post_id/destroy', to: 'likes#destroy', as: 'unlike'

  get 'posts/index'
  get 'posts/new', to: 'posts#new'
  get 'posts/:id/edit', to: 'posts#edit', as: 'posts_edit'
  post 'posts/create', to: 'posts#create'
  post 'posts/:id/update', to: 'posts#update', as: 'posts_update'
  delete 'posts/:id/delete', to: 'posts#destroy', as: 'posts_delete'

  get 'users/index'
  get 'users/:id', to: 'users#show', as: 'users_show'
  get 'users/:id/likes', to: 'users#likes', as: 'users_likes'
  get 'users/:id/edit', to: 'users#edit', as: 'users_edit'
  get 'signup', to: 'users#signup'
  get 'login', to: 'users#login_form'
  get 'users/:id/following', to: 'users#following'
  get 'users/:id/followers', to: 'users#followers'
  post 'users/create', to: 'users#create'
  post 'users/:id/update', to: 'users#update'
  post 'login', to: 'users#login'
  post 'logout', to: 'users#logout'

  resources :users do
    resource :relationships, only: %i[create destroy]
    get :follow, on: :member
    get :followers, on: :member
  end
end

app/views/shared/_posts_index.html.erb
<li class="postItem">
    <p class="postAuthor"><%= link_to post.user.username, users_show_path(post.user.id) %></p>
    <p class="date"><%= post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
    <div class="postBody">
        <p><%= post.content %></p>
    </div>
    <div class="postBottom">
        <% likes_count = post.likes.size %>
        <% if @posts_liked_by_current_user.include?(post.id) %>
            <%= link_to unlike_path(post.id), data: { turbo_method: :delete} do%>
                <div class="likes"><i class="fa-solid fa-heart like"></i><span><%= likes_count %></span></div>
            <% end %>
        <% else %>
            <%= link_to  like_path(post.id), data: { turbo_method: :post } do %>
                <div class="likes"><i class="fa-solid fa-heart unlike"></i><span><%= likes_count %></span></div>
            <% end %>
        <% end %>
        <% if @current_user == post.user %>
            <div class="buttons">
                <%= link_to "編集", posts_edit_path(post.id), class: "editBtn" %>
                <%= link_to  "削除", posts_delete_path(post.id), data: { turbo_method: :delete }, class: "deleteBtn" %>
            </div>
        <% end %>
    </div>
</li>