config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#top', as: 'route'

  post 'likes/:post_id/create', to: 'likes#create', as: 'like'
  delete 'likes/:post_id/destroy', to: 'likes#destroy', as: 'unlike'

  get 'posts/index'
  get 'posts/new', to: 'posts#new'
  get 'posts/:id/edit', to: 'posts#edit', as: 'posts_edit'
  post 'posts/create', to: 'posts#create'
  post 'posts/:id/update', to: 'posts#update', as: 'posts_update'
  delete 'posts/:id/delete', to: 'posts#destroy', as: 'posts_delete'

  get 'users/index'
  get 'users/:id', to: 'users#show', as: 'users_show'
  get 'users/:id/likes', to: 'users#likes', as: 'users_likes'
  get 'users/:id/edit', to: 'users#edit', as: 'users_edit'
  get 'signup', to: 'users#signup'
  get 'login', to: 'users#login_form'
  get 'users/:id/following', to: 'users#following'
  get 'users/:id/followers', to: 'users#followers'
  post 'users/create', to: 'users#create'
  post 'users/:id/update', to: 'users#update'
  post 'login', to: 'users#login'
  post 'logout', to: 'users#logout'

  resources :users do
    resource :relationships, only: %i[create destroy]
    get :follow, on: :member
    get :followers, on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  </head>
  <body>
    <% current_user = User.find_by(id: session[:user_id])%>
    <header class="header">
      <h1 class="headerTtl">
        <% if @current_user %>
          <%= link_to "Rails App", posts_index_path %>
        <% else %>
          <%= link_to "Rails App", route_path %>
        <% end %>
      </h1>
      <ul class="headerList">
        <% if current_user %>
          <li class="headerListItem">
            <%= link_to "ホーム", posts_index_path %>
          </li>
          <li class="headerListItem">
            <%= link_to "ユーザー一覧", users_index_path %>
          </li>
          <li class="headerListItem">
            <%= link_to "プロフィール", users_show_path(current_user.id) %>
          </li>
          <li class="headerListItem">
            <%= link_to "投稿する", posts_new_path %>
          </li>
          <li class="headerListItem">
            <%= link_to "ログアウト", logout_path, data: {turbo_method: :post} %>
          </li>
        <% else %>
          <li class="headerListItem">
            <%= link_to "新規登録", signup_path %>
          </li>
          <li class="headerListItem">
            <%= link_to "ログイン", login_path %>
          </li>
        <% end %>
      </ul>
    </header>
    <% if flash[:notice]%>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>